---
# Add 'cicd' label to any file changes inside .github dir
cicd:
  - .github/*
  - .github/**/*

# Add 'patterns' label to any file changes for the patterns
patterns:
  - source/_patterns/**

# Add 'documentation' label to any file changes for the documentation files
documentation:
  - ./**/*.md
