---
# Add 'cicd' label to any file changes inside .github dir
cicd:
  - changed-files:
      - any-glob-to-any-file: [".github/*", ".github/**/*"]

# Add 'patterns' label to any file changes for the patterns
patterns:
  - changed-files:
      - any-glob-to-any-file: "source/_patterns/**"

# Add 'documentation' label to any file changes for the documentation files
documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
