---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

default: true

###############
# Rules by id #
###############
MD004: false # Unordered list style
MD007: false
MD010: false
MD013:
  line_length: 1000 # Line length 80 is far to short
MD024: false #/no-duplicate-heading/no-duplicate-header
MD026:
  punctuation: ".,;:!。，；:" # List of not allowed
MD028: false
MD029: false # Ordered list item prefix
MD030: false
MD036: false # Emphasis used instead of a heading
MD049: false # emphasis-style Emphasis style should be consistent
MD053: false
#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
