#!/bin/sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname "$0")/_/husky.sh"

npx validate-branch-name
npx --yes pretty-quick --staged
npm run lint
node ./scripts/check-commit-mail.mjs
