#!/bin/sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname "$0")/_/husky.sh"

echo "### validate branch name ###"
npx validate-branch-name
echo "### lint staged files ###"
npx lint-staged
echo "### npm run lint ###"
npm run lint
echo "### check for commit mail ###"
node ./scripts/check-commit-mail.mjs
