name: Build Pages

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 🍼 Create pages build
        run: npm run build

      - name: ⬆ Upload dist
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: assets
          path: dist

      - name: ⬆ Upload sources
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: css-sources
          path: sources

      - name: ⬆ Upload out
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: patternlab
          path: out

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
