---
name: "Pull Request Labeler"
on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: 🏷️ Labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
